kind = "DojoContract"
class_hash = "0x53e5576693e2a8e889c296aa3c85c0ea72b549010fc2c6aa951a44afbe4e8ee"
original_class_hash = "0x53e5576693e2a8e889c296aa3c85c0ea72b549010fc2c6aa951a44afbe4e8ee"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dopewars-paper_mock-3534f748.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dopewars-paper_mock"
manifest_name = "dopewars-paper_mock-3534f748"
