kind = "DojoContract"
class_hash = "0x7d41b99e20ce5dbfd319359cac2e4fc3094244e3550aefbd7cf12b3c6cd3d2d"
original_class_hash = "0x7d41b99e20ce5dbfd319359cac2e4fc3094244e3550aefbd7cf12b3c6cd3d2d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dopewars-config-45ebce66.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dopewars-config"
manifest_name = "dopewars-config-45ebce66"
