kind = "DojoContract"
class_hash = "0x5a62bc5cb2d40fcb6415fa7b05b7185d36d4f54f01112471533835e0d12e220"
original_class_hash = "0x5a62bc5cb2d40fcb6415fa7b05b7185d36d4f54f01112471533835e0d12e220"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dopewars-store-49cb8012.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dopewars-store"
manifest_name = "dopewars-store-49cb8012"
