kind = "DojoContract"
class_hash = "0x5c110a7524e72a341a3573895e01f888adda24439c414ed3e4575321bbf905"
original_class_hash = "0x5c110a7524e72a341a3573895e01f888adda24439c414ed3e4575321bbf905"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dopewars-devtools-dd7a76fa.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dopewars-devtools"
manifest_name = "dopewars-devtools-dd7a76fa"
