kind = "DojoContract"
class_hash = "0x248b1168a17c70847374a1fc716504f7d539bdcda8dff0dacc93c160a956bff"
original_class_hash = "0x248b1168a17c70847374a1fc716504f7d539bdcda8dff0dacc93c160a956bff"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dopewars-game-4e7c9d90.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dopewars-game"
manifest_name = "dopewars-game-4e7c9d90"
