tag = "dopewars-devtools"
reads = []
writes = [
    "dopewars-SortedList",
    "dopewars-SortedListItem",
    "dopewars-Game",
    "dopewars-GameConfig",
    "dopewars-GameStorePacked",
    "dopewars-Season",
    "dopewars-SeasonSettings",
    "dopewars-RyoConfig",
]
init_calldata = []
