kind = "DojoModel"
class_hash = "0x77e6dc3b88082c043d32d9ade8875a0dbfd79ca8dff7fa21bbae69d1df96701"
original_class_hash = "0x77e6dc3b88082c043d32d9ade8875a0dbfd79ca8dff7fa21bbae69d1df96701"
abi = "manifests/ryosepolia/abis/base/models/rollyourown_utils_sorted_list_sorted_list_item.json"
name = "rollyourown::utils::sorted_list::sorted_list_item"

[[members]]
name = "list_id"
type = "felt252"
key = true

[[members]]
name = "item_k0"
type = "u32"
key = true

[[members]]
name = "item_k1"
type = "ContractAddress"
key = true

[[members]]
name = "next_k0"
type = "u32"
key = false

[[members]]
name = "next_k1"
type = "ContractAddress"
key = false
