kind = "DojoModel"
class_hash = "0x553c43e8511c15007bf6253d69cd177e5ff4a036355f33a0033a342e67301e0"
original_class_hash = "0x553c43e8511c15007bf6253d69cd177e5ff4a036355f33a0033a342e67301e0"
abi = "manifests/ryosepolia/abis/base/models/rollyourown_models_game_game.json"
name = "rollyourown::models::game::game"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "season_version"
type = "u16"
key = false

[[members]]
name = "game_mode"
type = "GameMode"
key = false

[[members]]
name = "player_name"
type = "Bytes16"
key = false

[[members]]
name = "hustler_id"
type = "u16"
key = false

[[members]]
name = "game_over"
type = "bool"
key = false

[[members]]
name = "final_score"
type = "u32"
key = false

[[members]]
name = "registered"
type = "bool"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false

[[members]]
name = "claimable"
type = "u32"
key = false

[[members]]
name = "position"
type = "u16"
key = false
