kind = "DojoModel"
class_hash = "0x35ba3415f4f97e6829c1326ce988c807b39fd54e68f91b50970379cff99d654"
original_class_hash = "0x35ba3415f4f97e6829c1326ce988c807b39fd54e68f91b50970379cff99d654"
abi = "manifests/ryosepolia/abis/base/models/rollyourown_config_encounters_encounter_stats_config.json"
name = "rollyourown::config::encounters::encounter_stats_config"

[[members]]
name = "encounter"
type = "Encounters"
key = true

[[members]]
name = "encounters_mode"
type = "EncountersMode"
key = true

[[members]]
name = "health_base"
type = "u8"
key = false

[[members]]
name = "health_step"
type = "u8"
key = false

[[members]]
name = "attack_base"
type = "u8"
key = false

[[members]]
name = "attack_step"
type = "u8"
key = false

[[members]]
name = "defense_base"
type = "u8"
key = false

[[members]]
name = "defense_step"
type = "u8"
key = false

[[members]]
name = "speed_base"
type = "u8"
key = false

[[members]]
name = "speed_step"
type = "u8"
key = false
