export const SCENE_KEYS = Object.freeze({
  PRELOAD_SCENE: "PRELOAD_SCENE",
  WORLD_SCENE: "WORLD_SCENE",
  // BATTLE_SCENE: 'BATTLE_SCENE',
  // TITLE_SCENE: 'TITLE_SCENE',
  // OPTIONS_SCENE: 'OPTIONS_SCENE',
});
