
[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x3677d8443f74dcc6cd23c4b3f217256c70f084ee7edc4ddc431af2ce91eb936"
keystore = "../../../sozo_acc"

[world]
name = "Dope Wars"
seed = "sepo6seed"
description = "Dope Wars is an onchain adaptation of the classic arbitrage game Drug Wars, built by Cartridge in partnership with Dope DAO."
# website = "https://rollyourown.preview.cartridge.gg/"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# socials.x = "https://x.com/TheDopeWars"

[namespace]
default = "dopewars"

[migration]
skip_contracts = ["dopewars-vrf_provider_mock"]

[init_call_args]
"dopewars-ryo" = [
    "0x0",                                                                # paper address, 0x0 = use dns world to retrieve paper_mock
    "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf address
    "0x44cea566ac53bf7c36b298e36536c1a53ba0b0bdf66b2c5f437965605acface",  # treasury: click_save controller address
]

[writers]
"dopewars" = [
    "dopewars-config",
    "dopewars-laundromat",
    "dopewars-game",
    "dopewars-decide",
    "dopewars-ryo",
    "dopewars-paper_mock",
]
"dopewars-ERC20BalanceEvent" = ["dopewars-paper_mock"]
"dopewars-GameConfig" = [
    "dopewars-config",
    "dopewars-laundromat",
    "dopewars-ryo",
]

"dopewars-DrugConfig" = ["dopewars-config"]
"dopewars-LocationConfig" = ["dopewars-config"]
"dopewars-HustlerItemBaseConfig" = ["dopewars-config"]
"dopewars-HustlerItemTiersConfig" = ["dopewars-config"]
"dopewars-EncounterStatsConfig" = ["dopewars-config"]

"dopewars-Game" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-GameStorePacked" = ["dopewars-game"]
"dopewars-RyoConfig" = ["dopewars-game", "dopewars-laundromat", "dopewars-ryo"]
"dopewars-Season" = ["dopewars-game", "dopewars-laundromat", "dopewars-ryo"]
"dopewars-SeasonSettings" = [
    "dopewars-game",
    "dopewars-laundromat",
    "dopewars-ryo",
]

"dopewars-SortedList" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-SortedListItem" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-RyoAddress" = ["dopewars-ryo"]

# events
"dopewars-GameCreated" = ["dopewars-game"]
"dopewars-Traveled" = ["dopewars-game"]
"dopewars-GameOver" = ["dopewars-game"]
"dopewars-TradeDrug" = ["dopewars-game"]
"dopewars-UpgradeItem" = ["dopewars-game"]
"dopewars-HighVolatility" = ["dopewars-game"]
"dopewars-TravelEncounter" = ["dopewars-game"]
"dopewars-TravelEncounterResult" = ["dopewars-game"]
#
"dopewars-NewSeason" = ["dopewars-laundromat"]
"dopewars-NewHighScore" = ["dopewars-laundromat"]
"dopewars-Claimed" = ["dopewars-laundromat"]

# bushido
"dopewars-TrophyProgression" = ["dopewars-game", "dopewars-laundromat"]
"dopewars-TrophyCreation" = ["dopewars-ryo"]
