
[env]
rpc_url = "https://api.cartridge.gg/x/ryo1/katana"
# account_address = "0x5087ef27f2ae9d2d88f5e5d9bf25b62afcc7a17f62aee5bd99654683f7e97"
# private_key = "0x592b2452182f46d4fd9ddc01d42f72b24ad33f51df4e1dbf1b1abece5dbed24"


[world]
name = "Dope Wars"
seed = "dopeseed"
description = "Dope Wars is an onchain adaptation of the classic arbitrage game Drug Wars, built by Cartridge in partnership with Dope DAO."
# website = "https://rollyourown.preview.cartridge.gg/"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# socials.x = "https://x.com/TheDopeWars"

[namespace]
default = "dopewars"

[migration]
skip_contracts = [
    "dopewars-slotmachine",
    "dopewars-SlotMachine",
    "dopewars-SlotMachineCombination",
    "dopewars-chips",
    "dopewars-devtools",
]

[init_call_args]
"dopewars-vrf_provider_mock" = [
    "0x6b0aab388dc7b240801b5aa0722bfcd39a1f397e83d5c032c198b18594b665e",
    "0x55ca1905d9b3d72b5e710f723c3bbd8f03428fb243f44cd5faee2796b44b204",
]
"dopewars-ryo" = [
    "0x0", # paper address, 0x0 = use dns world to retrieve paper_mock
    "0xe29882a1fcba1e7e10cad46212257fea5c752a4f9b1b1ec683c503a2cf5c8a", # treasury / multisig address
]

[writers]
"dopewars" = [
    "dopewars-config",
    "dopewars-laundromat",
    "dopewars-game",
    "dopewars-ryo",
]