kind = "DojoModel"
class_hash = "0x8b4ea6dfb414085c2f564de97d8ad1a1baaec39dabab34477903842f324141"
original_class_hash = "0x8b4ea6dfb414085c2f564de97d8ad1a1baaec39dabab34477903842f324141"
abi = "manifests/dev/base/abis/models/dopewars-Game-4462fb34.json"
tag = "dopewars-Game"
manifest_name = "dopewars-Game-4462fb34"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "season_version"
type = "u16"
key = false

[[members]]
name = "game_mode"
type = "GameMode"
key = false

[[members]]
name = "player_name"
type = "Bytes16"
key = false

[[members]]
name = "hustler_id"
type = "u16"
key = false

[[members]]
name = "game_over"
type = "bool"
key = false

[[members]]
name = "final_score"
type = "u32"
key = false

[[members]]
name = "registered"
type = "bool"
key = false

[[members]]
name = "claimed"
type = "bool"
key = false

[[members]]
name = "claimable"
type = "u32"
key = false

[[members]]
name = "position"
type = "u16"
key = false
