kind = "DojoModel"
class_hash = "0x6090567787eedc8eee8142111952d5aa5c7de6ee0a19b540461ac0ac62125ba"
original_class_hash = "0x6090567787eedc8eee8142111952d5aa5c7de6ee0a19b540461ac0ac62125ba"
abi = "manifests/dev/base/abis/models/dopewars-GameStorePacked-121912f1.json"
tag = "dopewars-GameStorePacked"
manifest_name = "dopewars-GameStorePacked-121912f1"

[[members]]
name = "game_id"
type = "u32"
key = true

[[members]]
name = "player_id"
type = "ContractAddress"
key = true

[[members]]
name = "packed"
type = "felt252"
key = false
