kind = "DojoModel"
class_hash = "0x4d20c5b72f4977e64a5f213ce489f22af9c3d9a79dddf12809620336f4aac"
original_class_hash = "0x4d20c5b72f4977e64a5f213ce489f22af9c3d9a79dddf12809620336f4aac"
abi = "manifests/dev/base/abis/models/dopewars-SortedList-4a8a13cf.json"
tag = "dopewars-SortedList"
manifest_name = "dopewars-SortedList-4a8a13cf"

[[members]]
name = "list_id"
type = "felt252"
key = true

[[members]]
name = "size"
type = "u32"
key = false

[[members]]
name = "locked"
type = "bool"
key = false

[[members]]
name = "processed"
type = "bool"
key = false

[[members]]
name = "process_max_size"
type = "u32"
key = false

[[members]]
name = "process_size"
type = "u32"
key = false

[[members]]
name = "process_cursor_k0"
type = "u32"
key = false

[[members]]
name = "process_cursor_k1"
type = "ContractAddress"
key = false
