kind = "DojoModel"
class_hash = "0x584d1b6dc875bd2ab9e2e9c4630d975b9a9f13e867784221bdb92913f3ac9c3"
original_class_hash = "0x584d1b6dc875bd2ab9e2e9c4630d975b9a9f13e867784221bdb92913f3ac9c3"
abi = "manifests/dev/base/abis/models/dopewars-HustlerItemBaseConfig-a462eb7d.json"
tag = "dopewars-HustlerItemBaseConfig"
manifest_name = "dopewars-HustlerItemBaseConfig-a462eb7d"

[[members]]
name = "slot"
type = "ItemSlot"
key = true

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "slot_id"
type = "u8"
key = false

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "initial_tier"
type = "u8"
key = false
