kind = "DojoModel"
class_hash = "0x4cd9d4399b8abcbafbd6037616783e5d574df1c99fe9e82e61a3dde30ef698"
original_class_hash = "0x4cd9d4399b8abcbafbd6037616783e5d574df1c99fe9e82e61a3dde30ef698"
abi = "manifests/dev/base/abis/models/dopewars-InitializableModel-11b94f3a.json"
tag = "dopewars-InitializableModel"
manifest_name = "dopewars-InitializableModel-11b94f3a"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "initialized"
type = "bool"
key = false
