kind = "DojoModel"
class_hash = "0x5e2fdb43459c0070413ffaa61d7025a2305455af2a050dd89bd99099dd93d69"
original_class_hash = "0x5e2fdb43459c0070413ffaa61d7025a2305455af2a050dd89bd99099dd93d69"
abi = "manifests/dev/base/abis/models/dopewars-DrugConfig-7c904f95.json"
tag = "dopewars-DrugConfig"
manifest_name = "dopewars-DrugConfig-7c904f95"

[[members]]
name = "drugs_mode"
type = "DrugsMode"
key = true

[[members]]
name = "drug"
type = "Drugs"
key = true

[[members]]
name = "drug_id"
type = "u8"
key = false

[[members]]
name = "base"
type = "u16"
key = false

[[members]]
name = "step"
type = "u16"
key = false

[[members]]
name = "weight"
type = "u16"
key = false

[[members]]
name = "name"
type = "Bytes16"
key = false
