kind = "DojoModel"
class_hash = "0x5843b992b183c8bb621c2f87f15fc2ed0cf9518a58adba31b368f9c2dbfa0f7"
original_class_hash = "0x5843b992b183c8bb621c2f87f15fc2ed0cf9518a58adba31b368f9c2dbfa0f7"
abi = "manifests/dev/base/abis/models/dopewars-HustlerItemTiersConfig-65f9f22c.json"
tag = "dopewars-HustlerItemTiersConfig"
manifest_name = "dopewars-HustlerItemTiersConfig-65f9f22c"

[[members]]
name = "slot"
type = "ItemSlot"
key = true

[[members]]
name = "tier"
type = "u8"
key = true

[[members]]
name = "slot_id"
type = "u8"
key = false

[[members]]
name = "cost"
type = "u32"
key = false

[[members]]
name = "stat"
type = "u32"
key = false
