kind = "DojoModel"
class_hash = "0x1ff318053105ed8851a98383eb50b5834c557d66d5d4647f3fb22eec9a1879d"
original_class_hash = "0x1ff318053105ed8851a98383eb50b5834c557d66d5d4647f3fb22eec9a1879d"
abi = "manifests/dev/base/abis/models/dopewars-Season-57a4b7ad.json"
tag = "dopewars-Season"
manifest_name = "dopewars-Season-57a4b7ad"

[[members]]
name = "version"
type = "u16"
key = true

[[members]]
name = "season_duration"
type = "u32"
key = false

[[members]]
name = "season_time_limit"
type = "u16"
key = false

[[members]]
name = "paper_fee"
type = "u16"
key = false

[[members]]
name = "treasury_fee_pct"
type = "u8"
key = false

[[members]]
name = "next_version_timestamp"
type = "u64"
key = false

[[members]]
name = "paper_balance"
type = "u32"
key = false

[[members]]
name = "high_score"
type = "u32"
key = false
