/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Game: (() => {
      const name = "Game";
      return defineComponent(
        world,
        {
          start_time: RecsType.Number,
          max_players: RecsType.Number,
          num_players: RecsType.Number,
          max_turns: RecsType.Number,
          is_finished: RecsType.Boolean,
          creator: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Market: (() => {
      const name = "Market";
      return defineComponent(
        world,
        {
          cash: RecsType.Number,
          quantity: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          status: RecsType.Number,
          location_id: RecsType.Number,
          cash: RecsType.Number,
          health: RecsType.Number,
          run_attempts: RecsType.Number,
          drug_count: RecsType.Number,
          bag_limit: RecsType.Number,
          turns_remaining: RecsType.Number,
          turns_remaining_on_death: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Drug: (() => {
      const name = "Drug";
      return defineComponent(
        world,
        {
          quantity: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Risks: (() => {
      const name = "Risks";
      return defineComponent(
        world,
        {
          travel: RecsType.Number,
          capture: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Name: (() => {
      const name = "Name";
      return defineComponent(
        world,
        {
          short_string: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
