tag = "dopewars-laundromat"
reads = []
writes = ["dopewars-SortedList","dopewars-SortedListItem","dopewars-Season","dopewars-SeasonSettings","dopewars-Game","dopewars-GameConfig","dopewars-RyoConfig"]
init_calldata = []
