tag = "dopewars-paper_mock"
reads = []
writes = [
    "dopewars-ERC20MetadataModel",
    "dopewars-ERC20BalanceModel",
    "dopewars-ERC20AllowanceModel",
    "dopewars-InitializableModel",
]
init_calldata = ["$contract_address:dopewars-laundromat"]
