[world]
kind = "WorldContract"
class_hash = "0x6b805e42fea7c91fc4b3362b37e4ddb485ffe08b4124cdefdc0fdfb005bcb48"
original_class_hash = "0x6b805e42fea7c91fc4b3362b37e4ddb485ffe08b4124cdefdc0fdfb005bcb48"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x2f569ad903a00476656bec6a74c954ef01e48202652bbab0149574d5f6d829"
transaction_hash = "0x781a8b074cd0ca0870e0bc49b9a734ee60aed0f410dc590ba777f9fd18e5782"
block_number = 1
seed = "rollyourown"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x69aa1a56046877011c8fd04a17fc286d5e97459bb5a6abf36420689dc13c317"
class_hash = "0x21f0d21a982ac5d3a1a2ea821846f32421b88316250364f61a4c96a08ce819f"
original_class_hash = "0x21f0d21a982ac5d3a1a2ea821846f32421b88316250364f61a4c96a08ce819f"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown__mocks_paper_mock_paper_mock.json"
reads = []
writes = [
    "ERC20MetadataModel",
    "ERC20BalanceModel",
    "ERC20AllowanceModel",
    "InitializableModel",
]
computed = []
init_calldata = ["$contract_address:rollyourown::systems::laundromat::laundromat"]
name = "rollyourown::_mocks::paper_mock::paper_mock"

[[contracts]]
kind = "DojoContract"
address = "0x2aac16fac599f6076a975c76e2a39ba3d44aa4b2f8ca5d0da0e985ed929677c"
class_hash = "0x58bee011b225a0c94800611a9a60f7c021d07cfc50993fcbade419d31fd3d4b"
original_class_hash = "0x58bee011b225a0c94800611a9a60f7c021d07cfc50993fcbade419d31fd3d4b"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_config_config_config.json"
reads = []
writes = [
    "GameConfig",
    "DrugConfig",
    "LocationConfig",
    "HustlerItemBaseConfig",
    "HustlerItemTiersConfig",
    "EncounterStatsConfig",
]
computed = []
init_calldata = []
name = "rollyourown::config::config::config"

[[contracts]]
kind = "DojoContract"
address = "0x1533726705c446acd88e4505c25caf6aceff0ea0c5dd1eb6ef83996d1b42b96"
class_hash = "0x425d8e3ec7c2935f527ff4591d1c02ca17bf07b1c6d6f52ca7b952d5adf872f"
original_class_hash = "0x425d8e3ec7c2935f527ff4591d1c02ca17bf07b1c6d6f52ca7b952d5adf872f"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_library_store_store.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::library::store::store"

[[contracts]]
kind = "DojoContract"
address = "0x2399758c6f6d325212660aa41cbebe17db95ee69d39ead9f81bfa0b24426c5d"
class_hash = "0x75251352946d36f6f93f9f780aa2542175528980ac2bca2d4b8217edc0569d5"
original_class_hash = "0x75251352946d36f6f93f9f780aa2542175528980ac2bca2d4b8217edc0569d5"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_systems_devtools_devtools.json"
reads = []
writes = [
    "SortedList",
    "SortedListItem",
    "Game",
    "GameConfig",
    "GameStorePacked",
    "Season",
    "SeasonSettings",
    "RyoConfig",
]
computed = []
init_calldata = []
name = "rollyourown::systems::devtools::devtools"

[[contracts]]
kind = "DojoContract"
address = "0x7b4f11739c0a600fec03b13d90fe348745ff512de83f7402d642d9581e3cde8"
class_hash = "0x2f3b57deb77c7ddf38d948d377df40e413f3633a0f644e0ee2bbaca6caee8e0"
original_class_hash = "0x2f3b57deb77c7ddf38d948d377df40e413f3633a0f644e0ee2bbaca6caee8e0"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_systems_game_game.json"
reads = []
writes = [
    "Game",
    "GameStorePacked",
    "RyoConfig",
    "Season",
    "SeasonSettings",
    "SortedList",
    "SortedListItem",
]
computed = []
init_calldata = []
name = "rollyourown::systems::game::game"

[[contracts]]
kind = "DojoContract"
address = "0x3da55aedc98cab0d565a9e90484ba41dd4ebb418db78bab84c92d9f8cf8a396"
class_hash = "0x337b3e3f9fc3ad259a238dbcab7ac6c5245d854488593b2f10039da930cb188"
original_class_hash = "0x337b3e3f9fc3ad259a238dbcab7ac6c5245d854488593b2f10039da930cb188"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_systems_laundromat_laundromat.json"
reads = []
writes = [
    "SortedList",
    "SortedListItem",
    "Season",
    "SeasonSettings",
    "Game",
    "GameConfig",
    "RyoConfig",
]
computed = []
init_calldata = []
name = "rollyourown::systems::laundromat::laundromat"

[[contracts]]
kind = "DojoContract"
address = "0x7723ad68899f78cd0b816ec304a462eb62344ef79718e4c5892845a6368db42"
class_hash = "0x14eba04e4e2716359874edf47e133fda64e72e718cab81a46eeeeb39c8d9b4f"
original_class_hash = "0x14eba04e4e2716359874edf47e133fda64e72e718cab81a46eeeeb39c8d9b4f"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/rollyourown_systems_ryo_ryo.json"
reads = []
writes = [
    "RyoConfig",
    "RyoAddress",
    "Season",
    "SeasonSettings",
]
computed = []
init_calldata = [
    "$contract_address:rollyourown::_mocks::paper_mock::paper_mock",
    "0xe29882a1fcba1e7e10cad46212257fea5c752a4f9b1b1ec683c503a2cf5c8a",
    "$contract_address:rollyourown::systems::laundromat::laundromat",
]
name = "rollyourown::systems::ryo::ryo"

[[models]]
kind = "DojoModel"
class_hash = "0x43ec1a1cd83de2b480bd3695bee9adce6aee21527d7e1e2ce56e54be460c2a4"
original_class_hash = "0x43ec1a1cd83de2b480bd3695bee9adce6aee21527d7e1e2ce56e54be460c2a4"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_drugs_drug_config.json"
name = "rollyourown::config::drugs::drug_config"

[[models.members]]
name = "drugs_mode"
type = "DrugsMode"
key = true

[[models.members]]
name = "drug"
type = "Drugs"
key = true

[[models.members]]
name = "drug_id"
type = "u8"
key = false

[[models.members]]
name = "base"
type = "u16"
key = false

[[models.members]]
name = "step"
type = "u16"
key = false

[[models.members]]
name = "weight"
type = "u16"
key = false

[[models.members]]
name = "name"
type = "Bytes16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x35ba3415f4f97e6829c1326ce988c807b39fd54e68f91b50970379cff99d654"
original_class_hash = "0x35ba3415f4f97e6829c1326ce988c807b39fd54e68f91b50970379cff99d654"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_encounters_encounter_stats_config.json"
name = "rollyourown::config::encounters::encounter_stats_config"

[[models.members]]
name = "encounter"
type = "Encounters"
key = true

[[models.members]]
name = "encounters_mode"
type = "EncountersMode"
key = true

[[models.members]]
name = "health_base"
type = "u8"
key = false

[[models.members]]
name = "health_step"
type = "u8"
key = false

[[models.members]]
name = "attack_base"
type = "u8"
key = false

[[models.members]]
name = "attack_step"
type = "u8"
key = false

[[models.members]]
name = "defense_base"
type = "u8"
key = false

[[models.members]]
name = "defense_step"
type = "u8"
key = false

[[models.members]]
name = "speed_base"
type = "u8"
key = false

[[models.members]]
name = "speed_step"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x75bb457a17fe9b19f25bbf0a3a820cefde7d339e5be06b3fa129517397fd5bc"
original_class_hash = "0x75bb457a17fe9b19f25bbf0a3a820cefde7d339e5be06b3fa129517397fd5bc"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_game_game_config.json"
name = "rollyourown::config::game::game_config"

[[models.members]]
name = "season_version"
type = "u16"
key = true

[[models.members]]
name = "cash"
type = "u32"
key = false

[[models.members]]
name = "health"
type = "u8"
key = false

[[models.members]]
name = "max_turns"
type = "u8"
key = false

[[models.members]]
name = "max_wanted_shopping"
type = "u8"
key = false

[[models.members]]
name = "max_rounds"
type = "u8"
key = false

[[models.members]]
name = "rep_drug_step"
type = "u8"
key = false

[[models.members]]
name = "rep_buy_item"
type = "u8"
key = false

[[models.members]]
name = "rep_carry_drugs"
type = "u8"
key = false

[[models.members]]
name = "rep_hospitalized"
type = "u8"
key = false

[[models.members]]
name = "rep_jailed"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3e8b16df9230d6a6e6e2b5957fee414fcc196cd2103a80df52d740452d260c2"
original_class_hash = "0x3e8b16df9230d6a6e6e2b5957fee414fcc196cd2103a80df52d740452d260c2"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_hustlers_hustler_item_base_config.json"
name = "rollyourown::config::hustlers::hustler_item_base_config"

[[models.members]]
name = "slot"
type = "ItemSlot"
key = true

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "slot_id"
type = "u8"
key = false

[[models.members]]
name = "name"
type = "felt252"
key = false

[[models.members]]
name = "initial_tier"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x234b62abcbf0769fe775e639db6ba250872d7cd071c773f466b1c7a0df0fe37"
original_class_hash = "0x234b62abcbf0769fe775e639db6ba250872d7cd071c773f466b1c7a0df0fe37"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_hustlers_hustler_item_tiers_config.json"
name = "rollyourown::config::hustlers::hustler_item_tiers_config"

[[models.members]]
name = "slot"
type = "ItemSlot"
key = true

[[models.members]]
name = "tier"
type = "u8"
key = true

[[models.members]]
name = "slot_id"
type = "u8"
key = false

[[models.members]]
name = "cost"
type = "u32"
key = false

[[models.members]]
name = "stat"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x667cfefc1e94c89bdf6fc345c86d28f9187ad7f35e22a6a9903d4cb32a20102"
original_class_hash = "0x667cfefc1e94c89bdf6fc345c86d28f9187ad7f35e22a6a9903d4cb32a20102"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_locations_location_config.json"
name = "rollyourown::config::locations::location_config"

[[models.members]]
name = "location"
type = "Locations"
key = true

[[models.members]]
name = "location_id"
type = "u8"
key = false

[[models.members]]
name = "name"
type = "Bytes16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6b246e4c2142a73be9e9585fa0a2a714a9b1150fd3f36a15025f3bfd757d204"
original_class_hash = "0x6b246e4c2142a73be9e9585fa0a2a714a9b1150fd3f36a15025f3bfd757d204"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_ryo_address_ryo_address.json"
name = "rollyourown::config::ryo_address::ryo_address"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "paper"
type = "ContractAddress"
key = false

[[models.members]]
name = "treasury"
type = "ContractAddress"
key = false

[[models.members]]
name = "laundromat"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3ba8161169e57bc5b8f1185cfcf49994fd0b2eb62869b175af514311af7a67b"
original_class_hash = "0x3ba8161169e57bc5b8f1185cfcf49994fd0b2eb62869b175af514311af7a67b"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_ryo_ryo_config.json"
name = "rollyourown::config::ryo::ryo_config"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models.members]]
name = "paused"
type = "bool"
key = false

[[models.members]]
name = "season_version"
type = "u16"
key = false

[[models.members]]
name = "season_duration"
type = "u32"
key = false

[[models.members]]
name = "season_time_limit"
type = "u16"
key = false

[[models.members]]
name = "paper_fee"
type = "u16"
key = false

[[models.members]]
name = "paper_reward_launderer"
type = "u16"
key = false

[[models.members]]
name = "treasury_fee_pct"
type = "u8"
key = false

[[models.members]]
name = "treasury_balance"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x41537a63c2a05be48536bb9cf2944f8e01eccbff657ae13106092010a8b65d9"
original_class_hash = "0x41537a63c2a05be48536bb9cf2944f8e01eccbff657ae13106092010a8b65d9"
abi = "manifests/dev/abis/deployments/models/rollyourown_config_settings_season_settings.json"
name = "rollyourown::config::settings::season_settings"

[[models.members]]
name = "season_version"
type = "u16"
key = true

[[models.members]]
name = "cash_mode"
type = "CashMode"
key = false

[[models.members]]
name = "health_mode"
type = "HealthMode"
key = false

[[models.members]]
name = "turns_mode"
type = "TurnsMode"
key = false

[[models.members]]
name = "encounters_mode"
type = "EncountersMode"
key = false

[[models.members]]
name = "encounters_odds_mode"
type = "EncountersOddsMode"
key = false

[[models.members]]
name = "drugs_mode"
type = "DrugsMode"
key = false

[[models.members]]
name = "wanted_mode"
type = "WantedMode"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x553c43e8511c15007bf6253d69cd177e5ff4a036355f33a0033a342e67301e0"
original_class_hash = "0x553c43e8511c15007bf6253d69cd177e5ff4a036355f33a0033a342e67301e0"
abi = "manifests/dev/abis/deployments/models/rollyourown_models_game_game.json"
name = "rollyourown::models::game::game"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "season_version"
type = "u16"
key = false

[[models.members]]
name = "game_mode"
type = "GameMode"
key = false

[[models.members]]
name = "player_name"
type = "Bytes16"
key = false

[[models.members]]
name = "hustler_id"
type = "u16"
key = false

[[models.members]]
name = "game_over"
type = "bool"
key = false

[[models.members]]
name = "final_score"
type = "u32"
key = false

[[models.members]]
name = "registered"
type = "bool"
key = false

[[models.members]]
name = "claimed"
type = "bool"
key = false

[[models.members]]
name = "claimable"
type = "u32"
key = false

[[models.members]]
name = "position"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3bdf1f27dc98fc67eaf4e8bebc05b7600db838a057131bd67ac216cab803e0f"
original_class_hash = "0x3bdf1f27dc98fc67eaf4e8bebc05b7600db838a057131bd67ac216cab803e0f"
abi = "manifests/dev/abis/deployments/models/rollyourown_models_game_store_packed_game_store_packed.json"
name = "rollyourown::models::game_store_packed::game_store_packed"

[[models.members]]
name = "game_id"
type = "u32"
key = true

[[models.members]]
name = "player_id"
type = "ContractAddress"
key = true

[[models.members]]
name = "packed"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x77af82d8b8683a2ed6d17fb5bb20080dfc3575bdf189ba228faf4caf3e181da"
original_class_hash = "0x77af82d8b8683a2ed6d17fb5bb20080dfc3575bdf189ba228faf4caf3e181da"
abi = "manifests/dev/abis/deployments/models/rollyourown_models_season_season.json"
name = "rollyourown::models::season::season"

[[models.members]]
name = "version"
type = "u16"
key = true

[[models.members]]
name = "season_duration"
type = "u32"
key = false

[[models.members]]
name = "season_time_limit"
type = "u16"
key = false

[[models.members]]
name = "paper_fee"
type = "u16"
key = false

[[models.members]]
name = "treasury_fee_pct"
type = "u8"
key = false

[[models.members]]
name = "next_version_timestamp"
type = "u64"
key = false

[[models.members]]
name = "paper_balance"
type = "u32"
key = false

[[models.members]]
name = "high_score"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3135a6d78ddca5643caf660d21e211a3f1384c30cbf99f94a360c28e28dd361"
original_class_hash = "0x3135a6d78ddca5643caf660d21e211a3f1384c30cbf99f94a360c28e28dd361"
abi = "manifests/dev/abis/deployments/models/rollyourown_utils_sorted_list_sorted_list.json"
name = "rollyourown::utils::sorted_list::sorted_list"

[[models.members]]
name = "list_id"
type = "felt252"
key = true

[[models.members]]
name = "size"
type = "u32"
key = false

[[models.members]]
name = "locked"
type = "bool"
key = false

[[models.members]]
name = "processed"
type = "bool"
key = false

[[models.members]]
name = "process_max_size"
type = "u32"
key = false

[[models.members]]
name = "process_size"
type = "u32"
key = false

[[models.members]]
name = "process_cursor_k0"
type = "u32"
key = false

[[models.members]]
name = "process_cursor_k1"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x77e6dc3b88082c043d32d9ade8875a0dbfd79ca8dff7fa21bbae69d1df96701"
original_class_hash = "0x77e6dc3b88082c043d32d9ade8875a0dbfd79ca8dff7fa21bbae69d1df96701"
abi = "manifests/dev/abis/deployments/models/rollyourown_utils_sorted_list_sorted_list_item.json"
name = "rollyourown::utils::sorted_list::sorted_list_item"

[[models.members]]
name = "list_id"
type = "felt252"
key = true

[[models.members]]
name = "item_k0"
type = "u32"
key = true

[[models.members]]
name = "item_k1"
type = "ContractAddress"
key = true

[[models.members]]
name = "next_k0"
type = "u32"
key = false

[[models.members]]
name = "next_k1"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
original_class_hash = "0x43d32948aa1be53f26e75e04da5ec56796f6e86030084b3ebede98c45ace32a"
abi = "manifests/dev/abis/deployments/models/token_components_security_initializable_initializable_model.json"
name = "token::components::security::initializable::initializable_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "initialized"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x304439814dd12e69d7898d226219e2fa2a374e82dae38f902c1b6a706bc8e82"
original_class_hash = "0x304439814dd12e69d7898d226219e2fa2a374e82dae38f902c1b6a706bc8e82"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc20_erc20_allowance_erc_20_allowance_model.json"
name = "token::components::token::erc20::erc20_allowance::erc_20_allowance_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "owner"
type = "ContractAddress"
key = true

[[models.members]]
name = "spender"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
original_class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc20_erc20_balance_erc_20_balance_model.json"
name = "token::components::token::erc20::erc20_balance::erc_20_balance_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u256"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1f925352eb45c770d7f13d2750ed4f8e58e3fd43000d33ceb845247a5bd7538"
original_class_hash = "0x1f925352eb45c770d7f13d2750ed4f8e58e3fd43000d33ceb845247a5bd7538"
abi = "manifests/dev/abis/deployments/models/token_components_token_erc20_erc20_metadata_erc_20_metadata_model.json"
name = "token::components::token::erc20::erc20_metadata::erc_20_metadata_model"

[[models.members]]
name = "token"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "symbol"
type = "ByteArray"
key = false

[[models.members]]
name = "decimals"
type = "u8"
key = false

[[models.members]]
name = "total_supply"
type = "u256"
key = false
