kind = "DojoModel"
class_hash = "0x41537a63c2a05be48536bb9cf2944f8e01eccbff657ae13106092010a8b65d9"
original_class_hash = "0x41537a63c2a05be48536bb9cf2944f8e01eccbff657ae13106092010a8b65d9"
abi = "manifests/ryo421/abis/base/models/rollyourown_config_settings_season_settings.json"
name = "rollyourown::config::settings::season_settings"

[[members]]
name = "season_version"
type = "u16"
key = true

[[members]]
name = "cash_mode"
type = "CashMode"
key = false

[[members]]
name = "health_mode"
type = "HealthMode"
key = false

[[members]]
name = "turns_mode"
type = "TurnsMode"
key = false

[[members]]
name = "encounters_mode"
type = "EncountersMode"
key = false

[[members]]
name = "encounters_odds_mode"
type = "EncountersOddsMode"
key = false

[[members]]
name = "drugs_mode"
type = "DrugsMode"
key = false

[[members]]
name = "wanted_mode"
type = "WantedMode"
key = false
