kind = "DojoModel"
class_hash = "0x234b62abcbf0769fe775e639db6ba250872d7cd071c773f466b1c7a0df0fe37"
original_class_hash = "0x234b62abcbf0769fe775e639db6ba250872d7cd071c773f466b1c7a0df0fe37"
abi = "manifests/ryo420/abis/base/models/rollyourown_config_hustlers_hustler_item_tiers_config.json"
name = "rollyourown::config::hustlers::hustler_item_tiers_config"

[[members]]
name = "slot"
type = "ItemSlot"
key = true

[[members]]
name = "tier"
type = "u8"
key = true

[[members]]
name = "slot_id"
type = "u8"
key = false

[[members]]
name = "cost"
type = "u32"
key = false

[[members]]
name = "stat"
type = "u32"
key = false
