kind = "DojoModel"
class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
original_class_hash = "0x291d91ffdce5772e40317feaf3b43873e8c716716d948b35c77c06c21fa4e9d"
abi = "manifests/ryo420/abis/base/models/token_components_token_erc20_erc20_balance_erc_20_balance_model.json"
name = "token::components::token::erc20::erc20_balance::erc_20_balance_model"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "account"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
