kind = "DojoContract"
class_hash = "0x3fbe921393a317edbf4ce56ca1f3785cd40f45dbbb636b6972d99e32a654d37"
original_class_hash = "0x3fbe921393a317edbf4ce56ca1f3785cd40f45dbbb636b6972d99e32a654d37"
base_class_hash = "0x0"
abi = "manifests/ryo420/abis/base/contracts/rollyourown__mocks_paper_mock_paper_mock.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::_mocks::paper_mock::paper_mock"
