kind = "DojoContract"
class_hash = "0x67a80ff23fd74c914e2d6141212eb43e7a20ad0a2610c191fdcc0ae93d69dc"
original_class_hash = "0x67a80ff23fd74c914e2d6141212eb43e7a20ad0a2610c191fdcc0ae93d69dc"
base_class_hash = "0x0"
abi = "manifests/ryo420/abis/base/contracts/rollyourown_systems_game_game.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::systems::game::game"
