kind = "DojoContract"
class_hash = "0x3497d49d47949a843f3398e3579dcac7df221da390774f6a64e2e3a37d22476"
original_class_hash = "0x3497d49d47949a843f3398e3579dcac7df221da390774f6a64e2e3a37d22476"
base_class_hash = "0x0"
abi = "manifests/ryo420/abis/base/contracts/rollyourown_systems_ryo_ryo.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::systems::ryo::ryo"
