kind = "DojoContract"
class_hash = "0x58bee011b225a0c94800611a9a60f7c021d07cfc50993fcbade419d31fd3d4b"
original_class_hash = "0x58bee011b225a0c94800611a9a60f7c021d07cfc50993fcbade419d31fd3d4b"
base_class_hash = "0x0"
abi = "manifests/ryo421/abis/base/contracts/rollyourown_config_config_config.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::config::config::config"
