import Head from "next/head";
import Image from "next/image";
import {
  Button,
  Center,
  Flex,
  Spacer,
  Text,
  useDisclosure,
  VStack,
} from "@chakra-ui/react";
import Connect from "@/components/icons/Connect";
import { useModal } from "@/components/Modal/ModalProvider";
import Cartridge from "@/components/icons/Cartridge";
import Argent from "@/components/icons/Argent";
import Container from "@/components/Container";
import { useAccount, useConnectors } from "@starknet-react/core";
import { argentConnector, controllerConnector } from "./_app";
import { formatAddress } from "@/utils";
import Disconnect from "@/components/icons/Disconnect";
import Players from "@/components/Players";
import Timer from "@/components/Timer";
import Lobby from "@/components/Lobby";
import Game from "@/components/Game";
import Cigarette from "@/components/icons/Cigarette";
import Header from "@/components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Center h="full">
            <Lobby addresses={["0x0"]} startInSeconds={500} />
            {/* <Game city={"brooklyn"} currentDay={0} totalDays={30} cashBalance={100}  /> */}
        </Center>
      </main>
    </>
  );
}
