kind = "DojoContract"
class_hash = "0x425d8e3ec7c2935f527ff4591d1c02ca17bf07b1c6d6f52ca7b952d5adf872f"
original_class_hash = "0x425d8e3ec7c2935f527ff4591d1c02ca17bf07b1c6d6f52ca7b952d5adf872f"
base_class_hash = "0x0"
abi = "manifests/ryosepolia/abis/base/contracts/rollyourown_library_store_store.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::library::store::store"
