kind = "DojoContract"
class_hash = "0x75251352946d36f6f93f9f780aa2542175528980ac2bca2d4b8217edc0569d5"
original_class_hash = "0x75251352946d36f6f93f9f780aa2542175528980ac2bca2d4b8217edc0569d5"
base_class_hash = "0x0"
abi = "manifests/ryosepolia/abis/base/contracts/rollyourown_systems_devtools_devtools.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::systems::devtools::devtools"
