kind = "DojoContract"
class_hash = "0x14eba04e4e2716359874edf47e133fda64e72e718cab81a46eeeeb39c8d9b4f"
original_class_hash = "0x14eba04e4e2716359874edf47e133fda64e72e718cab81a46eeeeb39c8d9b4f"
base_class_hash = "0x0"
abi = "manifests/ryosepolia/abis/base/contracts/rollyourown_systems_ryo_ryo.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::systems::ryo::ryo"
