kind = "DojoContract"
class_hash = "0x337b3e3f9fc3ad259a238dbcab7ac6c5245d854488593b2f10039da930cb188"
original_class_hash = "0x337b3e3f9fc3ad259a238dbcab7ac6c5245d854488593b2f10039da930cb188"
base_class_hash = "0x0"
abi = "manifests/ryosepolia/abis/base/contracts/rollyourown_systems_laundromat_laundromat.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "rollyourown::systems::laundromat::laundromat"
